services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: abc123xyz
      POSTGRES_USER: inventory_user
      POSTGRES_DB: inventory_db
    volumes:
      - ./docker-entrypoint-initdb.d/create-table.sql:/docker-entrypoint-initdb.d/create-table.sql
    ports:
      - "5432:5432"
